### ISSUE TITLE
Generator doesn't run npm install and bower install automatically

### ISSUE THREAD

**Issue by dfurtado** [dfurtado/generator-djangospa#7]
For some reason the generator is not installing the node and bower packages automatically.

**Comment by Nolapete** [comment]
Fixed https://github.com/robwierzbowski/generator-jekyllrb/commit/1c144c0f6b125a29801d93e8b17ec7466a513eb0 indicated to separate it out.  Another https://github.com/yeoman/generator/issues/752 indicated that once the end is called it will never run.

**Comment by dfurtado** [comment]
Awesome! Good it's solved now. :+1:
