### ISSUE TITLE
Warnings to be resolved

### ISSUE THREAD

**Issue by Nolapete** [dfurtado/generator-djangospa#8]
These happen during run of yo djangospa and should be resolved.

> npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^3.0.0.
> npm WARN prefer global node-gyp@3.2.0 should be installed with -g
> 
> npm WARN EPACKAGEJSON CBR@1.0.0 No repository field.
> npm WARN EPACKAGEJSON CBR@1.0.0 No license field.

**Comment by dfurtado** [comment]
Those warnings are not in generator but in some of the dependencies.
